apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testtest-testapp  #will be overitting by jenkins 
  namespace: argocd
  finalizers: []
spec:
  generators:
    - list:
        elements:
          - path: application1
          - path: application2
  template:
    metadata:
      name: 'testtest-{{path}}-testapp'
    spec:
      project: test
      source:
        repoURL: 'https://github.com/karami4yasser/gitopsDemo.git'
        targetRevision: main #will be overitting by jenkins   
        path: '{{path}}'
      destination:
        name: test 
        namespace: default  #will be overitting by jenkins 
        server: ''
      syncPolicy:
        syncOptions:
          - Replace=true
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true