apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: contains production App
  destinations:
  - name: in-cluster
    namespace: '*'
    server:  ''
  sourceRepos:
  - https://github.com/karami4yasser/gitopsDemo