apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: contains production App
  destinations:
  - name: prod
    namespace: default
    server: https://192.168.8.101:8443
  sourceRepos:
  - https://github.com/karami4yasser/gitopsDemo