apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
data:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://localhost:8090/job/DeleteBranch/build?token=114d6c543c0123e6f8b9f69ba9b69b156a
type: Opaque
