apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://admin:114d6c543c0123e6f8b9f69ba9b69b156a@localhost:8080/job/DeleteBranch/buildWithParameters?application=

type: Opaque