apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.github: |
    appID: 316041
    installationID: 36292525
    privateKey: $github-privateKey
  service.webhook.jenkins: |
    url: http://localhost:8090/job/DeleteBranch/build?token=114d6c543c0123e6f8b9f69ba9b69b156a
    basicAuth:
      username: yasser
      password: 114d6c543c0123e6f8b9f69ba9b69b156a
  subscriptions: |
    - recipients:
      - jenkins
      triggers:
      - on-sync-status-unknown
    - recipients:
      - github
      triggers:
      - on-sync-running
    - recipients:
      - github
      triggers:
      - on-deployed
    - recipients:
      - github
      triggers:
      - on-sync-succeeded
    - recipients:
      - github
      triggers:
      - on-health-degraded
    - recipients:
      - github
      triggers:
      - on-sync-failed
  template.app-sync-status-unknown : |
    message: |
      Application {{.app.metadata.name}} is now Umown new version of deployments manifests.
    jenkins:
      method: GET
  template.app-sync-running : |
    message: |
      Application {{.app.metadata.name}} is now pending new version of deployments manifests.
    github:
      status:
        state: pending
        label: "{{.app.metadata.name}}"
        targetURL: "http://localhost:8080/applications/{{.app.metadata.name}}?operation=true"
  template.app-sync-succeeded : |
    message: |
      Application {{.app.metadata.name}} is now succeeded new version of deployments manifests.
    github:
      status:
        state: success
        label: "{{.app.metadata.name}}"
        targetURL: "http://localhost:8080/applications/{{.app.metadata.name}}?operation=true"
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status:
        state: success
        label: "{{.app.metadata.name}}"
        targetURL: "http://localhost:8080/applications/{{.app.metadata.name}}?operation=true"
  template.app-health-degraded: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status:
        state: failure
        label: "{{.app.metadata.name}}"
        targetURL: "http://localhost:8080/applications/{{.app.metadata.name}}?operation=true"
  template.app-sync-failed: |
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
    github:
      status:
        state: failure
        label: "{{.app.metadata.name}}"
        targetURL: "http://localhost:8080/applications/{{.app.metadata.name}}?operation=true"
  trigger.on-sync-status-unknown: | 
    - when: app.status.sync.status in ['Syncing','Unknown']
      send: [app-sync-status-unknown]
  trigger.on-sync-running: |
    - when: app.status.operationState.phase in ['Running']
      send: [app-sync-running,app-sync-status-unknown]
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded,app-sync-status-unknown]
  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Deployed']
      send: [app-deployed,app-sync-status-unknown]
  trigger.on-health-degraded: |
    - when: app.status.operationState.phase in ['Degraded','Missing',Failed,'Error']
      send: [app-health-degraded,app-sync-status-unknown]
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed,app-sync-status-unknown]
