apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testapppullrequest #will be overitting by jenkins 
  namespace: argocd
  finalizers: []
spec:
  generators:
    - pullRequest:
        github:
          owner: karami4yasser
          repo: gitopsDemo
    - list:
        elements:
          - path: application1
          - path: application2
  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'
    spec:
      project: test
      source:
        repoURL: 'https://github.com/karami4yasser/gitopsDemo.git'
        targetRevision: '{{head_sha}}' #will be overitting by jenkins   
        path: '{{path}}'
      destination:
        name: test 
        namespace: myapp-{{branch}}-{{number}}  #will be overitting by jenkins 
        server: ''
      syncPolicy:
        syncOptions:
          - Replace=true
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true